apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  # https://github.com/redhat-developer/web-terminal-operator
  - target:
      group: workspace.devfile.io
      kind: DevWorkspaceTemplate
    patch: |-
      - op: add
        path: /metadata/annotations/web-terminal.redhat.com~1unmanaged-state
        value: 'true'
      - op: replace
        path: /spec/components/0/container/args
        value:
          - "/bin/bash"
          - "-c"
          - |
            #!/bin/bash
            GIT_REPO=https://github.com/codekow/demo-ai-gitops-catalog.git

            echo "
              echo
              echo 'This terminal has been enhanced.'
              echo See ${GIT_REPO}
            " >> ~/.bashrc

            git clone "${GIT_REPO}" gitops

            echo "
              cd gitops; . scripts/functions.sh; cd ..

            __git_branch(){
              git name-rev --name-only @ 2>/dev/null
            }

            PS1='\e]\s\a\n\e[33m\w \e[36m\$(__git_branch)\e[m$ '

            [ -e ~/.venv/bin/activate ] && . ~/.venv/bin/activate
            [ -e ~/gitops/scratch/bin/restic.bash ] && . ~/gitops/scratch/bin/restic.bash

            " >> ~/.bashrc

            cd gitops
            . scripts/functions.sh

            [ -d ~/.venv ] || pyvenv-3.6 ~/.venv

            bin_check busybox

            bin_check oc_mirror
            bin_check rclone
            bin_check restic

            sleep infinity
