apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- pvc.yaml

patches:
  - target:
      kind: Deployment
      name: pgadmin4
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/name
        value: pgadmin-data
      - op: replace
        path: /spec/template/spec/volumes
        value:
          - persistentVolumeClaim:
              claimName: pgadmin4-pvc
            name: pgadmin4-data
