apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intel-demos-gitops

bases:
  - ../../../../defaults/openshift-gitops/instance/overlays/default

patches:
  - path: patch-rbac.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ArgoCD
