apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-etcd

resources:
- ../../base
- pvc.yaml


patches:
  - target:
      kind: CronJob
      name: etcd-backup
    patch: |
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/volumes/2
        value:
          name: etcd-backup
          persistentVolumeClaim:
            claimName: etcd-backup
