apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-vector-add
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-vector-add
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nvidia-vector-add
    spec:
      containers:
        - name: minion
          image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.7.1-ubuntu20.04"
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              while true
              do
                nvidia-smi
                /cuda-samples/vectorAdd
              done
          resources:
            limits:
              nvidia.com/gpu: 1
