apiVersion: v1
kind: ConfigMap
metadata:
  name: device-plugin-config
data:
  default: |-
    version: v1
  time-sliced-2: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
          - name: nvidia.com/gpu
            replicas: 2
  time-sliced-4: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
          - name: nvidia.com/gpu
            replicas: 4
