apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-rhoai-configuration/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-shared-app/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-shared-database/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-shared-img-det/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-shared-llm/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-shared-milvus/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-shared-minio/base?ref=dev
  - https://github.com/rh-aiservices-bu/parasol-insurance/bootstrap/ic-user-projects/base?ref=dev

patches:
  - target:
      kind: PersistentVolumeClaim
      namespace: ic-shared-llm
    patch: |-
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteOnce
      - op: remove
        path: /spec/storageClassName
  - target:
      kind: Deployment
      name: llm
      namespace: ic-shared-llm
    patch: |-
      - op: replace
        path: /spec/template/spec/tolerations
        value:
          - effect: NoSchedule
            key: nvidia.com/gpu
            operator: Exists
  - path: exclude-sc-ceph-rbd.yaml
  - path: exclude-sc-gp3.yaml
  - path: exclude-cm.yaml
  - path: exclude-acc-profile.yaml
  - path: patch-dsc.yaml
