apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-puller

resources:
- ../../../../../components/cluster-configs/kustomized/image-puller/base

patches:
  - target:
      group: apps
      kind: DaemonSet
      name: image-puller
    patch: |-
      - op: replace
        path: /metadata/name
        value: image-puller-pipelines
      - op: replace
        path: /spec/template/spec/tolerations
        value:
          - effect: NoSchedule
            key: nvidia.com/gpu
            operator: Exists
      - op: replace
        path: /spec/template/spec/containers
        value:
          - name: ds-pipeline-runtime-image-confidence
            image: quay.io/rh-aiservices-bu/rhoai-lab-insurance-claim-confidence-pipeline:1.1
            command:
              - sleep
              - infinity
            resources:
              limits:
                memory: 20Mi
              requests:
                cpu: 10m
                memory: 10Mi
