- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-nvidia-gpu-operator
        path: components/operators/nvidia-gpu-operator/aggregate/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-openshift-nfd
        path: components/operators/openshift-nfd-operator/aggregate/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-rhods
        path: components/operators/rhods-operator/operator/overlays/stable
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-sealed-secrets
        path: components/operators/sealed-secrets/operator/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-web-terminal
        path: components/operators/web-terminal/operator/overlays/fast
