- op: add
  path: /spec/generators/0/list/elements
  value:
    # - cluster: local
    #   url: https://kubernetes.default.svc
    #   values:
    #     name: config-cluster-certs
    #     namespace: openshift-gitops
    #     path: components/configs/cluster-certs/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-console
        namespace: openshift-gitops
        path: components/configs/console/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-login
        namespace: openshift-config
        path: components/configs/login/overlays/rhdp
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-base-namespaces
        namespace: openshift-gitops
        path: components/configs/namespaces/overlays/default-limited
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-rbac
        namespace: openshift-gitops
        path: components/configs/rbac/overlays/rhdp
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-sandbox-cleanup
        namespace: openshift-gitops
        path: components/configs/simple/sandbox-cleanup
