apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

# Banner Notice
- banner-data.yaml

# Cluster Login
# - ../../components/configs/cluster/login/overlays/htpasswd

# Image Registry Config
- ../../components/configs/cluster/registry/overlays/empty-dir

# OpenShift Logging
- ../../components/operators/cluster-logging/operator/overlays/stable

# Node Maintenance Operator
- ../../components/operators/node-maintenance-operator/operator/overlays/stable

# Nvidia GPU Operator
- ../../components/operators/gpu-operator-certified/instance/overlays/default
- ../../components/operators/gpu-operator-certified/operator/overlays/stable

# Nvidia Network Operator
- ../../components/operators/nvidia-network-operator/operator/overlays/24.1.0

# NmState Operator
- ../../components/operators/kubernetes-nmstate-operator/operator/overlays/stable

# Loki
- ../../components/operators/loki-operator/operator/overlays/stable-5.8

# Node Feature Discovery - for Nvidia
- ../../components/operators/nfd/instance/overlays/only-nvidia
- ../../components/operators/nfd/operator/overlays/stable

# OpenShift Pipelines
- ../../components/operators/openshift-pipelines-operator-rh/operator/overlays/latest

# Advanced Cluster Security
- ../../components/operators/advanced-cluster-security/instance/overlays/default
- ../../components/operators/advanced-cluster-security/operator/overlays/latest

# Red Hat SSO
- ../../components/operators/rhsso-operator/operator/overlays/stable

# OpenShift Service Mesh
- ../../components/operators/servicemeshoperator/operator/overlays/stable

# OpenShift Web Terminal
- ../../components/operators/web-terminal/instance/overlays/enhanced
- ../../components/operators/web-terminal/operator/overlays/fast

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Day 2 Operations w/ GitOps'
