apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../configs/cluster/console/overlays/default
  - ../../../operators/rhods-operator/operator/overlays/stable
  - ../../../operators/openshift-pipelines-operator-rh/operator/overlays/latest
  - ../../kustomized/rhods
  - ../../kustomized/rhods-projects
  - ../../kustomized/custom-notebook-images/overlays/rhods

patches:
  - target:
      kind: ConsoleNotification
      name: banner-top
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Red Hat Open Data Science (RHODS)'
  - target:
      group: user.openshift.io
      version: v1
      kind: Group
      name: workshop-users
    path: patch-workshop-users.yaml
