- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-cluster-rbac
        namespace: openshift-gitops
        path: components/configs/rbac/overlays/rhdp
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-console
        namespace: openshift-gitops
        path: components/configs/console/base
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-base-namespaces
        namespace: openshift-gitops
        path: components/configs/namespaces/aggregate/rhdp
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-idm-login
        namespace: openshift-gitops
        path: components/configs/login/overlays/rhdp
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: config-sandbox-cleanup
        namespace: openshift-gitops
        path: components/configs/simple/sandbox-cleanup
