apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../components/rhoai

resources:
  - ../../base
  - ../../../components/operators/rhods-operator/instance/overlays/minimal

patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Red Hat OpenShift AI (RHOAI) - Minimal'
