- op: add
  path: /spec/generators/0/list/elements
  value:
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-ack-controllers
        path: components/operators/ack-controllers/aggregate/popular
    # - cluster: local
    #   url: https://kubernetes.default.svc
    #   values:
    #     name: operator-openshift-logging
    #     path: components/operators/openshift-logging/aggregate/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-openshift-nfd
        path: components/operators/openshift-nfd-operator/aggregate/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-openshift-pipelines
        path: components/operators/openshift-pipelines/operator/overlays/latest
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-nvidia-gpu-operator
        path: components/operators/nvidia-gpu-operator/aggregate/overlays/default
    # - cluster: local
    #   url: https://kubernetes.default.svc
    #   values:
    #     name: prometheus-user-workload-monitoring
    #     path: components/operators/prometheus-monitoring/instance/overlays/user-workload-monitoring
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-sealed-secrets
        path: components/operators/sealed-secrets/operator/overlays/default
    - cluster: local
      url: https://kubernetes.default.svc
      values:
        name: operator-web-terminal
        path: components/operators/web-terminal-operator/operator/overlays/fast
