apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: demo-cleanup
    namespace: adhoc-admin
    files:
      - ocp-default-crds-4.16.txt
      - namespaces.txt
      - uninstall.sh
 
patches:
  - path: patch-job.yaml
    target:
      kind: Job
      name: adhoc-admin-helper
