apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.17/deploy/examples/csi/cephfs/snapshotclass.yaml
  # - https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.17/deploy/examples/csi/cephfs/storageclass.yaml
  # - https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.17/deploy/examples/filesystem.yaml
  - storage.yaml

# patches:
#   - path: exclude-subvol.yaml
