---
# Source: mlflow-server/templates/objectbucketclaim.yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: release-name-mlflow-server
  labels:
    helm.sh/chart: mlflow-server-0.6.4
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.10"
    app.kubernetes.io/managed-by: Helm
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: release-name-mlflow-server
  storageClassName: openshift-storage.noobaa.io
