---
# Source: mlflow-server/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: release-name-mlflow-server
  labels:
    helm.sh/chart: mlflow-server-0.6.4
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.10"
    app.kubernetes.io/managed-by: Helm
spec:
  to:
    kind: Service
    name: release-name-mlflow-server
    weight: 100
  port:
    targetPort: oauth
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
