apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../demos/overlays/rhoai-workshop-ready

patches:
  - path: patch-dsc.yaml
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Red Hat OpenShift AI (RHOAI) - Parasol Insurance Workshop'
  - target:
      kind: Subscription
      name: rhods-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable
      # - op: replace
      #   path: /spec/installPlanApproval
      #   value: Manual
      - op: add
        path: /spec/startingCSV
        value: rhods-operator.2.22.1
  - target:
      kind: Job
      name: job-aws-gpu-machineset
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: INSTANCE_TYPE
          value: g5.2xlarge
  # - target:
  #     kind: Subscription
  #     name: gpu-operator-certified
  #   patch: |-
  #     - op: replace
  #       path: /spec/channel
  #       value: v23.6
  #     # - op: replace
  #     #   path: /spec/installPlanApproval
  #     #   value: Manual
  #     - op: add
  #       path: /spec/startingCSV
  #       value: gpu-operator-certified.v23.6.0
  # - target:
  #     kind: ConfigMap
  #     name: job-aws-gpu-machineset
  #   patch: |-
  #     - op: replace
  #       path: /data/job.sh
  #       value: |
  #         #!/bin/bash

  #         # shellcheck disable=SC1091
  #         . /scripts/ocp.sh

  #         ocp_aws_cluster || exit 0
  #         ocp_aws_machineset_create_gpu g5.2xlarge
  #         ocp_machineset_create_autoscale
