- op: replace
  path: /spec/template/spec/source/repoURL
  value: 'git@github.com:redhat-na-ssa/demo-argocd-gitops.git'
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: testing
